//
// File generated by rootcint at Tue Jan 17 13:21:42 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PxEventDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PxEventDictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void PxEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_PxEvent(void *p = 0);
   static void *newArray_PxEvent(Long_t size, void *p);
   static void delete_PxEvent(void *p);
   static void deleteArray_PxEvent(void *p);
   static void destruct_PxEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PxEvent*)
   {
      ::PxEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PxEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PxEvent", ::PxEvent::Class_Version(), "./PxEvent.h", 57,
                  typeid(::PxEvent), DefineBehavior(ptr, ptr),
                  &::PxEvent::Dictionary, isa_proxy, 4,
                  sizeof(::PxEvent) );
      instance.SetNew(&new_PxEvent);
      instance.SetNewArray(&newArray_PxEvent);
      instance.SetDelete(&delete_PxEvent);
      instance.SetDeleteArray(&deleteArray_PxEvent);
      instance.SetDestructor(&destruct_PxEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PxEvent*)
   {
      return GenerateInitInstanceLocal((::PxEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PxEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *PxEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PxEvent::Class_Name()
{
   return "PxEvent";
}

//______________________________________________________________________________
const char *PxEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PxEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PxEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PxEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PxEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PxEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PxEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PxEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void PxEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class PxEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(PxEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(PxEvent::Class(),this);
   }
}

//______________________________________________________________________________
void PxEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PxEvent.
      TClass *R__cl = ::PxEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerNumber_", &triggerNumber_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerBcoNumber_", &triggerBcoNumber_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcoNumber_", &bcoNumber_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rawHits_", (void*)&rawHits_);
      R__insp.InspectMember("vector<uint32_t>", (void*)&rawHits_, "rawHits_.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PxDecodedHits_", (void*)&PxDecodedHits_);
      R__insp.InspectMember("vector<PxDecodedHit>", (void*)&PxDecodedHits_, "PxDecodedHits_.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_PxEvent(void *p) {
      return  p ? new(p) ::PxEvent : new ::PxEvent;
   }
   static void *newArray_PxEvent(Long_t nElements, void *p) {
      return p ? new(p) ::PxEvent[nElements] : new ::PxEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_PxEvent(void *p) {
      delete ((::PxEvent*)p);
   }
   static void deleteArray_PxEvent(void *p) {
      delete [] ((::PxEvent*)p);
   }
   static void destruct_PxEvent(void *p) {
      typedef ::PxEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::PxEvent

namespace ROOT {
   void vectorlEPxDecodedHitgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEPxDecodedHitgR_Dictionary();
   static void *new_vectorlEPxDecodedHitgR(void *p = 0);
   static void *newArray_vectorlEPxDecodedHitgR(Long_t size, void *p);
   static void delete_vectorlEPxDecodedHitgR(void *p);
   static void deleteArray_vectorlEPxDecodedHitgR(void *p);
   static void destruct_vectorlEPxDecodedHitgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<PxDecodedHit>*)
   {
      vector<PxDecodedHit> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<PxDecodedHit>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<PxDecodedHit>", -2, "prec_stl/vector", 49,
                  typeid(vector<PxDecodedHit>), DefineBehavior(ptr, ptr),
                  0, &vectorlEPxDecodedHitgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<PxDecodedHit>) );
      instance.SetNew(&new_vectorlEPxDecodedHitgR);
      instance.SetNewArray(&newArray_vectorlEPxDecodedHitgR);
      instance.SetDelete(&delete_vectorlEPxDecodedHitgR);
      instance.SetDeleteArray(&deleteArray_vectorlEPxDecodedHitgR);
      instance.SetDestructor(&destruct_vectorlEPxDecodedHitgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<PxDecodedHit> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<PxDecodedHit>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEPxDecodedHitgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<PxDecodedHit>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEPxDecodedHitgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<PxDecodedHit> : new vector<PxDecodedHit>;
   }
   static void *newArray_vectorlEPxDecodedHitgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<PxDecodedHit>[nElements] : new vector<PxDecodedHit>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEPxDecodedHitgR(void *p) {
      delete ((vector<PxDecodedHit>*)p);
   }
   static void deleteArray_vectorlEPxDecodedHitgR(void *p) {
      delete [] ((vector<PxDecodedHit>*)p);
   }
   static void destruct_vectorlEPxDecodedHitgR(void *p) {
      typedef vector<PxDecodedHit> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<PxDecodedHit>

namespace ROOT {
   void vectorlEunsignedsPintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEunsignedsPintgR_Dictionary();
   static void *new_vectorlEunsignedsPintgR(void *p = 0);
   static void *newArray_vectorlEunsignedsPintgR(Long_t size, void *p);
   static void delete_vectorlEunsignedsPintgR(void *p);
   static void deleteArray_vectorlEunsignedsPintgR(void *p);
   static void destruct_vectorlEunsignedsPintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<unsigned int>*)
   {
      vector<unsigned int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<unsigned int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<unsigned int>", -2, "vector.dll", 0,
                  typeid(vector<unsigned int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEunsignedsPintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<unsigned int>) );
      instance.SetNew(&new_vectorlEunsignedsPintgR);
      instance.SetNewArray(&newArray_vectorlEunsignedsPintgR);
      instance.SetDelete(&delete_vectorlEunsignedsPintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEunsignedsPintgR);
      instance.SetDestructor(&destruct_vectorlEunsignedsPintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<unsigned int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<unsigned int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEunsignedsPintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<unsigned int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEunsignedsPintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned int> : new vector<unsigned int>;
   }
   static void *newArray_vectorlEunsignedsPintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned int>[nElements] : new vector<unsigned int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEunsignedsPintgR(void *p) {
      delete ((vector<unsigned int>*)p);
   }
   static void deleteArray_vectorlEunsignedsPintgR(void *p) {
      delete [] ((vector<unsigned int>*)p);
   }
   static void destruct_vectorlEunsignedsPintgR(void *p) {
      typedef vector<unsigned int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<unsigned int>

/********************************************************
* PxEventDictionary.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePxEventDictionary();

extern "C" void G__set_cpp_environmentPxEventDictionary() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PxEvent.h");
  G__cpp_reset_tagtablePxEventDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevPxEventDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PxEvent */
static int G__PxEventDictionary_177_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PxEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PxEvent[n];
     } else {
       p = new((void*) gvp) PxEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PxEvent;
     } else {
       p = new((void*) gvp) PxEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PxEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new PxEvent((int64_t) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) PxEvent((int64_t) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const PxEvent*) G__getstructoffset())->getTriggerNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const PxEvent*) G__getstructoffset())->getTriggerBcoNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 108, (long) ((const PxEvent*) G__getstructoffset())->getBCONumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const PxEvent*) G__getstructoffset())->getNumberOfHits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const PxEvent*) G__getstructoffset())->getRawHit((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<uint32_t>& obj = ((const PxEvent*) G__getstructoffset())->getRawHits();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const PxDecodedHit* pobj;
         const PxDecodedHit xobj = ((const PxEvent*) G__getstructoffset())->getDecodedHit((unsigned int) G__int(libp->para[0]));
         pobj = new PxDecodedHit(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<PxDecodedHit>& obj = ((const PxEvent*) G__getstructoffset())->getDecodedHits();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->setTriggerNumber((int32_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->setTriggerBcoNumber((int32_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->setBCONumber((int64_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->setRawHit((uint32_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->setRawHits(*(vector<uint32_t>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->setDecodedHit(*(PxDecodedHit*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->setDecodedHits(*(vector<PxDecodedHit>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         PxEvent* pobj;
         PxEvent xobj = ((PxEvent*) G__getstructoffset())->operator+=(*(PxEvent*) libp->para[0].ref);
         pobj = new PxEvent(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PxEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PxEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PxEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PxEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PxEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PxEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PxEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PxEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PxEventDictionary_177_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PxEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PxEventDictionary_177_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PxEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PxEvent(*(PxEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PxEvent G__TPxEvent;
static int G__PxEventDictionary_177_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PxEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PxEvent*) (soff+(sizeof(PxEvent)*i)))->~G__TPxEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PxEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PxEvent*) (soff))->~G__TPxEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PxEventDictionary_177_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PxEvent* dest = (PxEvent*) G__getstructoffset();
   *dest = *(PxEvent*) libp->para[0].ref;
   const PxEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PxEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPxEventDictionary {
 public:
  G__Sizep2memfuncPxEventDictionary(): p(&G__Sizep2memfuncPxEventDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPxEventDictionary::*p)();
};

size_t G__get_sizep2memfuncPxEventDictionary()
{
  G__Sizep2memfuncPxEventDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePxEventDictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent))) {
     PxEvent *G__Lderived;
     G__Lderived=(PxEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent),G__get_linked_tagnum(&G__PxEventDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePxEventDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("int32_t",105,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("int64_t",108,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("uint32_t",104,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint32_t>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PxDecodedHit>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PxEvent */
static void G__setup_memvarPxEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent));
   { PxEvent *p; p=(PxEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("int32_t"),-1,4,"triggerNumber_=",0,"-1 means untriggered event");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("int32_t"),-1,4,"triggerBcoNumber_=",0,"-1 means untriggered event");
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("int64_t"),-1,4,"bcoNumber_=",0,"-1 means no bco information");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<uint32_t>"),-1,4,"rawHits_=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR),G__defined_typename("vector<PxDecodedHit>"),-1,4,"PxDecodedHits_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PxEventDictionaryLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPxEventDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPxEvent(void) {
   /* PxEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent));
   G__memfunc_setup("PxEvent",714,G__PxEventDictionary_177_0_1, 105, G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PxEvent",714,G__PxEventDictionary_177_0_2, 105, G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent), -1, 0, 1, 1, 1, 0, "l - 'int64_t' 0 - bcoNumber", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTriggerNumber",1661,G__PxEventDictionary_177_0_3, 105, -1, G__defined_typename("int32_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTriggerBcoNumber",1937,G__PxEventDictionary_177_0_4, 105, -1, G__defined_typename("int32_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBCONumber",1149,G__PxEventDictionary_177_0_5, 108, -1, G__defined_typename("int64_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNumberOfHits",1526,G__PxEventDictionary_177_0_6, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getRawHit",911,G__PxEventDictionary_177_0_7, 104, -1, G__defined_typename("uint32_t"), 0, 1, 1, 1, 8, "h - - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getRawHits",1026,G__PxEventDictionary_177_0_8, 117, G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR), G__defined_typename("vector<uint32_t>"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDecodedHit",1293,G__PxEventDictionary_177_0_9, 117, G__get_linked_tagnum(&G__PxEventDictionaryLN_PxDecodedHit), -1, 0, 1, 1, 1, 8, "h - - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDecodedHits",1408,G__PxEventDictionary_177_0_10, 117, G__get_linked_tagnum(&G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR), G__defined_typename("vector<PxDecodedHit>"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTriggerNumber",1673,G__PxEventDictionary_177_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'int32_t' 0 - triggerNumber", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTriggerBcoNumber",1949,G__PxEventDictionary_177_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'int32_t' 0 - triggerBcoNumber", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setBCONumber",1161,G__PxEventDictionary_177_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "l - 'int64_t' 0 - bcoNumber", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRawHit",923,G__PxEventDictionary_177_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'uint32_t' 0 - rawHit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRawHits",1038,G__PxEventDictionary_177_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<unsigned int,allocator<unsigned int> >' 'vector<uint32_t>' 11 - rawHits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDecodedHit",1305,G__PxEventDictionary_177_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'PxDecodedHit' - 11 - PxDecodedHit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDecodedHits",1420,G__PxEventDictionary_177_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<PxDecodedHit,allocator<PxDecodedHit> >' 'vector<PxDecodedHit>' 11 - PxDecodedHits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+=",980,G__PxEventDictionary_177_0_18, 117, G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent), -1, 0, 1, 1, 1, 0, "u 'PxEvent' - 11 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PxEventDictionary_177_0_19, 85, G__get_linked_tagnum(&G__PxEventDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PxEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PxEventDictionary_177_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PxEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PxEventDictionary_177_0_21, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PxEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PxEventDictionary_177_0_22, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PxEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PxEventDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PxEventDictionary_177_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PxEventDictionary_177_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PxEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PxEventDictionary_177_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PxEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PxEventDictionary_177_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PxEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PxEventDictionary_177_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PxEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("PxEvent", 714, G__PxEventDictionary_177_0_31, (int) ('i'), G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent), -1, 0, 1, 1, 1, 0, "u 'PxEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PxEvent", 840, G__PxEventDictionary_177_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PxEventDictionary_177_0_33, (int) ('u'), G__get_linked_tagnum(&G__PxEventDictionaryLN_PxEvent), -1, 1, 1, 1, 1, 0, "u 'PxEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPxEventDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPxEventDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPxEventDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PxEventDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_PxDecodedHit = { "PxDecodedHit" , 115 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_PxEvent = { "PxEvent" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR = { "vector<PxDecodedHit,allocator<PxDecodedHit> >" , 99 , -1 };
G__linked_taginfo G__PxEventDictionaryLN_reverse_iteratorlEvectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PxDecodedHit,allocator<PxDecodedHit> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePxEventDictionary() {
  G__PxEventDictionaryLN_TClass.tagnum = -1 ;
  G__PxEventDictionaryLN_TBuffer.tagnum = -1 ;
  G__PxEventDictionaryLN_TMemberInspector.tagnum = -1 ;
  G__PxEventDictionaryLN_TObject.tagnum = -1 ;
  G__PxEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__PxEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PxEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PxEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PxEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PxEventDictionaryLN_PxDecodedHit.tagnum = -1 ;
  G__PxEventDictionaryLN_PxEvent.tagnum = -1 ;
  G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR.tagnum = -1 ;
  G__PxEventDictionaryLN_reverse_iteratorlEvectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePxEventDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_PxDecodedHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_PxEvent),sizeof(PxEvent),-1,324864,(char*)NULL,G__setup_memvarPxEvent,G__setup_memfuncPxEvent);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR);
   G__get_linked_tagnum_fwd(&G__PxEventDictionaryLN_reverse_iteratorlEvectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupPxEventDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupPxEventDictionary()");
  G__set_cpp_environmentPxEventDictionary();
  G__cpp_setup_tagtablePxEventDictionary();

  G__cpp_setup_inheritancePxEventDictionary();

  G__cpp_setup_typetablePxEventDictionary();

  G__cpp_setup_memvarPxEventDictionary();

  G__cpp_setup_memfuncPxEventDictionary();
  G__cpp_setup_globalPxEventDictionary();
  G__cpp_setup_funcPxEventDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPxEventDictionary();
  return;
}
class G__cpp_setup_initPxEventDictionary {
  public:
    G__cpp_setup_initPxEventDictionary() { G__add_setup_func("PxEventDictionary",(G__incsetup)(&G__cpp_setupPxEventDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPxEventDictionary() { G__remove_setup_func("PxEventDictionary"); }
};
G__cpp_setup_initPxEventDictionary G__cpp_setup_initializerPxEventDictionary;

