######################################################################
# Automatically generated by qmake (3.0) Thu Jun 22 16:01:08 2017
######################################################################

TEMPLATE = app
TARGET = treemodel
INCLUDEPATH += .

# Input
HEADERS += domitem.h dommodel.h mainwindow.h
SOURCES += domitem.cpp dommodel.cpp main.cpp mainwindow.cpp
