/********************************************************************
* PxEventDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PxEventDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePxEventDictionary();
extern void G__cpp_setup_inheritancePxEventDictionary();
extern void G__cpp_setup_typetablePxEventDictionary();
extern void G__cpp_setup_memvarPxEventDictionary();
extern void G__cpp_setup_globalPxEventDictionary();
extern void G__cpp_setup_memfuncPxEventDictionary();
extern void G__cpp_setup_funcPxEventDictionary();
extern void G__set_cpp_environmentPxEventDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PxEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PxEventDictionaryLN_TClass;
extern G__linked_taginfo G__PxEventDictionaryLN_TBuffer;
extern G__linked_taginfo G__PxEventDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__PxEventDictionaryLN_TObject;
extern G__linked_taginfo G__PxEventDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__PxEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PxEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PxEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PxEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PxEventDictionaryLN_PxDecodedHit;
extern G__linked_taginfo G__PxEventDictionaryLN_PxEvent;
extern G__linked_taginfo G__PxEventDictionaryLN_vectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgR;
extern G__linked_taginfo G__PxEventDictionaryLN_reverse_iteratorlEvectorlEPxDecodedHitcOallocatorlEPxDecodedHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
